# https://github.com/kubernetes/ingress-nginx/blob/main/charts/ingress-nginx/values.yaml
---

controller:
  service:
    enabled: true
    externalTrafficPolicy: Local
  resources:
    limits:
      cpu: 200m
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 128Mi
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
      additionalLabels:
        release: prometheus
