---
# _1 postfix in case of multiple resources of same type (e.g. vpc_2, vpc_3, etc... in the same dev env)
vpc_1:
  vpc_name: "dev-env"
  vpc_cidr: "10.0.0.0/16"

ecr_1:
  repo_name: "dev-env-ecr"

eks_1:
  eks_cluster_name: "alex-demo"
  eks_version: "1.29"

ec2_1:
  ec2_name: "demo-ec2"

sg_ec2:
  sg_ec2_name: "sg-ec2"
