---
name: prod-tf
cluster_name: production
# VPC
cidr: 10.200.0.0/16
# EKS services
enabled_services:
  - argo-cd
  - nginx-controller
  - cert-manager
  - aws-efs-csi-driver
# ECR
ecr_repositories:
  karpenter-demo: {}
  checker: {}
  webapp: {}
  # Production
  naviteq-site:
    repository_force_delete: false
    repository_image_tag_mutability: MUTABLE
# Route3
